### ISSUE TITLE
为什么插件导出来的alpha video 和 市面上的视频 黑白色视频是反着的

### ISSUE THREAD

**Issue by QiuYeHong90** [yylive/YYEVA#10]
市面上的黑白色视频 是在左侧 你们的是在右侧😄

**Comment by guoyabiniOS** [comment]
YYEVA的三端：[iOS](https://github.com/yylive/yyeva-ios)、[android](https://github.com/yylive/yyeva-android)、[web](https://github.com/yylive/yyeva-web)在渲染的时候，都是按左侧RGB、右侧Alpha来读取渲染的。

**Comment by TangBaoo** [comment]
加载时有参数可以控制取RGB 从右侧吗

**Comment by ckken** [comment]
> 加载时有参数可以控制取RGB 从右侧吗

web 有
