### ISSUE TITLE
ae插件导出时候能不能像lottie 的bodymovin那种一样，不需要自己做蒙版，直接设置下就导出就好了

### ISSUE THREAD

**Issue by linzzzzllll** [yylive/YYEVA#11]
ae插件导出时候能不能像lottie 的bodymovin那种一样，不需要自己做蒙版，直接设置下就导出就好了

**Comment by linzzzzllll** [comment]
> ae插件导出时候能不能像lottie 的bodymovin那种一样，不需要自己做蒙版，直接设置下就导出就好了

蒙版是那个动画的大蒙版，

**Comment by yymoneygroup** [comment]
fix 下载最新的ae插件
