### ISSUE TITLE
求助，Mac上AE插件无法导出MP4

### ISSUE THREAD

**Issue by Lucius0610** [yylive/YYEVA#13]
· 按教程设置了AE输出模板，使用插件导出显示导出成功，但在导出目录下没有MP4文档，查看temp中有Mov文件，日志显示导出成功；
· AE版本22.6.0，系统版本11.6.5，插件版本2.3.5；
· 安全性与隐私权限全开，系统没有拦截ffmpeg的提示；
-------------
· 另外请问Alpha通道视频必须要自己制作和RGB拼在一起吗？

**Comment by guoyabiniOS** [comment]
1.可以加入QQ群：981738110，提交下日志文件给我们，有可能是输出的路径指定到了其他路径。
2. 如果是非Mov格式的输出合成，Alpha通道的合成插件内部可以自动生成  [文档](https://juejin.cn/post/7175045566496243772)有描述哈

**Comment by Lucius0610** [comment]
在群里技术大佬给解决了，分享一下给后面来看的同学，好像还是插件没有下载到ffmpeg，可以自己手动下载一个放在/Library/Application Support/Adobe/CEP/extensions/com.yy.aeconverterformp4/localbin/mac/
