### ISSUE TITLE
求助 windows 11 ae20  最新版插件 提示请检查项目合法性

### ISSUE THREAD

**Issue by hm123456coder** [yylive/YYEVA#16]
![image](https://github.com/yylive/YYEVA/assets/127595860/5a2d08b4-30e8-4b2a-b7ac-7caac026afba)

**Comment by hm123456coder** [comment]
选择路径时 提示 请检查所选项目合法性

**Comment by qqnp1100** [comment]
一样的问题，有解决方法吗

**Comment by ynot16** [comment]
先保存一下项目哈，如果不行可以加qq群咨询下
