### ISSUE TITLE
同一个EvaView连续播放不同视频

### ISSUE THREAD

**Issue by anypwx** [yylive/YYEVA#19]
1. 能在同一个view 上  播放一个视频后  接着播放另一个视频吗？
2. 能在同一个view 上  播放一个视频中，中断播放 然后播放另一个视频？

**Comment by ganpenglong** [comment]
这不是非常通用的接口需求，建议业务方基于YYEVA播放器，自己实现对应业务功能。
我们有提供播放和暂停的接口，可以基于提供的基础接口实现业务需求。
