### ISSUE TITLE
ios存在内存泄漏问题

### ISSUE THREAD

**Issue by ZL335408** [yylive/YYEVA#30]
我用官方提供的demo播放同一视频资源发现内存存在不断上涨，播放的视频资源越大内存上涨的现象更明显。有没有什么好的办法解决一下

**Comment by ynot16** [comment]
我这边试了不会，你是最新的代码吗？或者可以加qq群详聊

**Comment by ZL335408** [comment]
问题已解决，直接pod下来的是旧版，pod的时候需要跟上版本号即可

**Comment by ZL335408** [comment]
问题已解决，直接pod下来的是旧版，pod的时候需要跟上版本号即可
