### ISSUE TITLE
IOS H265 hvc1兼容

### ISSUE THREAD

**Issue by sakuradeathgithub** [yylive/YYEVA#33]
由于ios的AVFundation只支持以hvc1标记的h265视频,而工具导出的默认h265是以hev1标记的,无法再ios播放,是否有隐藏的选项可以调整标记方式,或者是否有更新计划
![9d28fdef4a570ca4c50893cfcc435419](https://github.com/user-attachments/assets/0b66f291-826c-4855-9cf3-7e52bd469861)

**Comment by ynot16** [comment]
最新的插件已经是导出hvc1的了发自我的 iPhone在 2024年12月13日，11:56，sakuradeathgithub ***@***.***> 写道：﻿
由于ios的AVFundation只支持以hvc1标记的h265视频,而工具导出的默认h265是以hev1标记的,无法再ios播放,是否有隐藏的选项可以调整标记方式,或者是否有更新计划
9d28fdef4a570ca4c50893cfcc435419.png (view on web)

**Comment by sakuradeathgithub** [comment]
好的,感谢
