### ISSUE TITLE
你好，请问是否支持在线播放以及音效

### ISSUE THREAD

**Issue by alfservice** [yylive/YYEVA#4]

**Comment by ckken** [comment]
撇开浏览器的限制 是可以的 具体可以参考 [mute](https://github.com/yylive/YYEVA-Web/tree/main/packages/yyeva#%E9%85%8D%E7%BD%AE)
https://github.com/yylive/YYEVA-Web/blob/main/packages/yyeva/src/player/index.ts#L133

**Comment by guoyabiniOS** [comment]
iOS >= 1.0.3 已支持含音频播放的功能
