### ISSUE TITLE
MP4透明处理中左右不对称时是怎么取到alpha值的？

### ISSUE THREAD

**Issue by fengyima** [yylive/YYEVA#6]
原有的左右对称的MP4视频，可以在根据左边的点找到右边的点rgb值，现在右边已经被缩放了一倍放在了右上角，那如何再根据像素点找到对应的右边像素点？
例如：
旧MP4：假设视频宽高是400*400，左边点坐标[10,10]，那要获取的alpha值坐标[210,10]
新MP4的坐标点该怎么取呢？

**Comment by guoyabiniOS** [comment]
请查看[数据结构](https://github.com/yylive/YYEVA/blob/main/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.md)篇有给到数据定义
