### ISSUE TITLE
视频填充模式问题

### ISSUE THREAD

**Issue by ETmanwenhan** [yylive/YYEVA#8]
目前视频模式为scalefill , 会导致视频画面被拉伸变形。
1. 建议默认填充模式：aspectFill，等比例缩放，超出部分被裁决. 防止画面变形
2. 建议暴露自定义视频填充模式方法，让开发者自定义

非常感谢！

**Comment by ETmanwenhan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢你联系我。我会尽快给您回复。

**Comment by guoyabiniOS** [comment]
[iOS仓库](https://github.com/yylive/yyeva-ios) 更新 1.0.5，提供了此功能
