### ISSUE TITLE
YYEVAPlayer是否支持网络url加载mp4动画呢？

### ISSUE THREAD

**Issue by ETmanwenhan** [yylive/YYEVA#9]
YYEVAPlayer不支持网络url加载mp4动画吗?

建议：同时支持本地mp4和网络mp4会更人性化些，动画库就更加完美. 加入更加方便。
可以考虑采用系统的网络下载资源，类似SVGA中的下载功能.
参考：https://github.com/svga/SVGAPlayer-iOS/blob/master/Source/SVGAParser.m
或参考：https://github.com/ETmanwenhan/SVGAPlayer-iOS/blob/2.5.7_fix/Source/SVGAParser.m // 接入了NSURLCache

非常感谢大神们!

**Comment by guoyabiniOS** [comment]
已在Example工程里提供了网络下载的相关Demo 
[iOS](https://github.com/yylive/YYEVA-iOS/blob/main/Example/YYEVA/YYEVAPlayer%2BHttpURL.h)
[android](https://github.com/yylive/YYEVA-Android/commit/8e0fb409efb1cb19f15f0b86033f4102afd0cec6)
